module.exports.themesById = {
    44: "romance",
    43: "mystery",
    42: "erotic",
    41: "4x-explore-expand-exploit-and-exterminate",
    40: "party",
    39: "warfare",
    38: "open-world",
    35: "kids",
    34: "educational",
    33: "sandbox",
    32: "non-fiction",
    31: "drama",
    28: "business",
    27: "comedy",
    23: "stealth",
    22: "historical",
    21: "survival",
    20: "thriller",
    19: "horror",
    18: "science-fiction",
    17: "fantasy",
    13: "simulator",
    12: "role-playing-rpg",
    11: "real-time-strategy-rts",
    10: "racing",
    9: "puzzle",
    8: "platform",
    7: "music",
    5: "shooter",
    4: "fighting",
    2: "point-and-click",
    1: "action"
};

module.exports.genresById = {
    2: "point-and-click",
    4: "fighting",
    5: "shooter",
    7: "music",
    8: "platform",
    9: "puzzle",
    10: "racing",
    11: "real-time-strategy-rts",
    12: "role-playing-rpg",
    13: "simulator"
};
